### ISSUE TITLE
Design Layout - Carissa

### ISSUE THREAD

**Issue by willblakemeyer** [willblakemeyer/RestaurantRoulette#2]

**Comment by carissalk** [comment]
https://xd.adobe.com/view/b037297d-9b79-4cc7-9029-70d628729e00-e564/

**Comment by carissalk** [comment]
![Image](https://github.com/willblakemeyer/RestaurantRoulette/assets/81452708/7356e004-fd18-41c8-813d-96469f4f0931)



![Image](https://github.com/willblakemeyer/RestaurantRoulette/assets/81452708/0dd867f4-ba03-4e78-b6a3-d5935793274f)
